# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        products:
            uri_prefix: /images/avatars
            upload_destination: 'http://localhost:5173/src/assets/images/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer